### PR TITLE
fix: game sound issue solved by path adjust using audio src tag as path provider

### LINKED ISSUE #1: read sound file in vscode webview
### Which part does this bug appears?(or the part you guess)

Platform

### Link to the code that reproduces this issue

_No response_

### To Reproduce

If I put my audio files in game folder, 
the platform does not play audio file.

### Current vs. Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by junman95**
# Pull Request Template

## Type of PR

- [ ] Feature - Platform
- [ ] Feature - Game
- [x] Fix - Bug

## Description of PR
- Fix game sound issue

## Changes Made
- fix by assigning path provider audio tag

## Related Issues
close #1 

## Checklist

- [x] Prepared for code review (Assignees set, Labels applied, etc.)
- [x] Checked that changes do not negatively affect existing features
- [ ] Documentation completed for new features
- [ ] All unit tests passed
- [ ] Testing in the test environment completed
- [x] Linked this PR in the related issue
- [x] Communicated sufficiently with the relevant team or person before submitting PR

### CODE REVIEW

File: resource/game/tetris/sound.js [hunk 1]
```diff
@@ -1,71 +1,75 @@
...
+    true
+  ),
+  movesSound = sound.create(`${soundPathDiv.src}/moves.mp3`, "moves_sound"),
+  dropSound = sound.create(`${soundPathDiv.src}/drop.mp3`, "drop_sound"),
+  pointsSound = sound.create(`${soundPathDiv.src}/points.mp3`, "points_sound"),
+  finishSound = sound.create(`${soundPathDiv.src}/finish.mp3`, "finish_sound");
 sound.muteToggle();
-sound.soundSetting();
\ No newline at end of file
+sound.soundSetting();
```
Comment (junman95) [inline resource/game/tetris/sound.js:75]: changes made here

**Review by XPECTER — APPROVED** [review]

**Review by Ooyd — COMMENTED** [review]
Thanks for consolidating the path settings with the creation of soundPathDiv

**Review by Ooyd — APPROVED** [review]
